# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-14 17:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='comment_preview',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
